### ISSUE TITLE
Seemingly valid answer not accepted in "Iteration can be used for repetition"

### ISSUE THREAD

**Issue by firoxer** [functional-koans/clojure-koans#101]
In the final lazy sequence koan `conj` is not considered a valid answer as in `(= (repeat 100 :foo) (take 100 (iterate conj :foo)))`.

I checked that the accepted answer is `(fn [x] x)`. I ran `(= (take 100 (iterate conj :foo)) (take 100 (iterate (fn [x] x) :foo)))` on http://clojurescript.net/ to test that the different inputs have equal answers and got `true` as result.

**Comment by trptcolin** [comment]
Ah yes, I can see why that would be surprising! 

Under the hood, the first element of `(iterate conj :foo)` is generated by `(conj :foo)`. In ClojureScript (which you're seeing some version of on http://clojurescript.net), `(conj :foo)` evaluates to `:foo`, and so you get `:foo` 100 times in the result. I'm actually not sure why that's the case - maybe some implementation detail? Normally `conj` takes 2 or more arguments. Here's the documentation, from a local `lein repl` session:

```clojure
user=> (doc conj)
-------------------------
clojure.core/conj
([coll x] [coll x & xs])
  conj[oin]. Returns a new collection with the xs
    'added'. (conj nil item) returns (item).  The 'addition' may
    happen at different 'places' depending on the concrete type.
```

In Clojure (which is similar to, but a different language than, ClojureScript), `(conj :foo)` throws an exception (check it out on http://www.tryclj.com/, which is running Clojure). I also highly recommend trying things out locally, using a tool like [Leiningen](https://github.com/technomancy/leiningen) (via `lein repl`).

**Comment by firoxer** [comment]
Oh, alright. Sorry for bothering without having tried in a local REPL first. At least I learnt something new. Case closed!

**Comment by trptcolin** [comment]
No worries!

**Comment by ode79** [comment]
In `lein repl` `(conj :foo)` doesn't throw an exception, it returns `:foo`.

**Comment by samflores** [comment]
Probably `tryclj` is still running Clojure 1.6, since 1.7 introduced these (undocumented) arities to `conj`: clojure/clojure@2a09172e0c3285ccdf79d1dc4d399d190678b670

**Comment by trptcolin** [comment]
Ah right, transducers. Thanks y'all - I was on an old point release of lein.

But then this becomes more confusing, because on the current master branch of clojure-koans (which depends on clojure 1.7.0), I'm seeing this input pass under `lein koan run`:

```
  "Iteration can be used for repetition"
  (= (repeat 100 :hello)
     (take 100 (iterate conj :hello))))
```

which makes sense given this new & undocumented arity of `conj`. But then what caused the issue that triggered this issue in the first place?

@firoxer were you possibly on an older release of the clojure-koans, and/or not using Leiningen to run the koans? I know you've got your question answered now, but it'd be great to make sure there's no nondeterministic version stuff in play here.

**Comment by firoxer** [comment]
I was trying out http://clojurescriptkoans.com/ (https://github.com/lazerwalker/clojurescript-koans).

I figured this was the repo for the koans but was mistaken. I had thought the only differences between ClojureScript and Clojure are related to the environment and not the core library and didn't really think things through before posting an issue. I should have RTFM first :disappointed:

**Comment by trptcolin** [comment]
Ahhhh, got it, makes sense. Thanks for letting us know, and no worries at all! Strange things come up from time to time, so just wanted to rule those out!
