### ISSUE TITLE
Conj for maps?

### ISSUE THREAD

**Issue by Futurile** [functional-koans/clojure-koans#112]
In 03_lists and 04_vectors conj is used to add values to a collection. In 06_maps assoc is used - should there be an example using conj as well? Conj works to add a collection->map, but I'm not sure if it's idiomatic?

**Comment by trptcolin** [comment]
Good idea! Yeah, that'd be a nice addition. Want to open a PR for it? It'd mean a new description/test entry in the maps file, as well as an answer key entry to make sure `lein koan test` is still all good (see https://github.com/functional-koans/clojure-koans#contributing)

**Comment by Futurile** [comment]
The example in lists/vector files is showing how to add 'an item' to the type. For maps 'assoc' is used for maps.

Conj doesn't work to just add a bare item to a map, but it is possible to use conj to add another map, or a vector of two items:

```
repl=> (conj {:a 1 :b 2} {:c 3 :d 4} {:e 6})
{:a 1, :b 2, :c 3, :d 4, :e 6}
```

Though this post says it may be vestigal and that merge should be used (http://grokbase.com/t/gg/clojure/11b825hywg/%60conj%60-into-maps)

From this reading and the examples on clojure docs I believe it would be better to show using merge, like this:

```
repl=> (merge {:a 1 :b 2} {:c 3 :d 4} {:e 6})
{:a 1, :b 2, :c 3, :d 4, :e 6}

```

Do you agree?

I started on a small PR, but how do I get it to fill in more than two blanks? In 06_maps I added:

````
(= {:a 1 :b 2 __ __ __ __} (merge {:a 1 :b 2} {:c 3 :d 4}))
```
In koans.clj I added:

```
                :c 3 :d 4
```
But, 'lein koan  test' complains:

```
#error {
 :cause "Duplicate key: __"
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.lang.IllegalArgumentException: Duplicate key: __, compiling:(null:45:29)"
   :at [clojure.lang.Compiler load "Compiler.java" 7386]}
  {:type java.lang.IllegalArgumentException
   :message "Duplicate key: __"
   :at [clojure.lang.PersistentArrayMap createWithCheck "PersistentArrayMap.java" 71]}]
```

Thanks!

**Comment by trptcolin** [comment]
Ah, yes: map literals aren't allowed to have the same key, so `{:a 1 :b 2 __ __ __ __}` is illegal (but using the `set` function to construct a map will just remove duplicates).

Choices to fix: 
1. Make one of the maps have only a single entry, e.g. `{:c 3}`
2. Change the expected map to be constructed by the `set` function, like `(set [:a 1 :b 2 __ __ __ __])`

Either way seems OK in my book. And I agree, it's rare to see `conj` in practice; `merge` is more common. Good idea.

**Comment by Futurile** [comment]
Decided to take option 1 as it makes it simple to understand the concept. PR #113

**Comment by trptcolin** [comment]
Thanks again for tackling this; closing the issue since the PR is merged.
