### ISSUE TITLE
Strict description of the rules

### ISSUE THREAD

**Issue by hiredgunhouse** [functional-koans/clojure-koans#124]
It's not clear whether I am only allowed to touch the ___ parts of code in order to make tests pass or can I make changes outside ___ too?
For instance this test from destructuring seems pretty hard to solve if I'm only allowed to touch the ___  part.:
```clojure
  "All together now!"
  (= "Test Testerson, 123 Test Lane, Testerville, TX"
     (___ ["Test" "Testerson"] test-address)))
```

**Comment by trptcolin** [comment]
Yep, only those parts that look like blanks to fill in. Sometimes solutions might be more complicated expressions, which is fine. There's a way to do it, for sure - but from my perspective, if you have another way that creates a top-level function or something, go for it!

**Comment by hiredgunhouse** [comment]
Ok, thx!
BTW. Thank you for making those koans, they are awesome!
