### ISSUE TITLE
Provide a way to run other 'sets' of koans

### ISSUE THREAD

**Issue by wcravens** [functional-koans/clojure-koans#133]
The model of koans is excellent.  But I would really like to develop other 'sets' of koans that are independent of the core koans.

For example, I would like to be able to create a new directory of koans, `src/my_new_set_of_koans` with it's own `resources/my_new_set_of_koans.clj`.

In fact a 'plugin' model of sorts may be even more interesting.  So, separating the koan runner from the koan provider.

**Comment by trptcolin** [comment]
Sounds like you want https://github.com/functional-koans/clojure-koan-engine ?

**Comment by wcravens** [comment]
Bazinga!
