### ISSUE TITLE
[feature] Extract Koan Engine?

### ISSUE THREAD

**Issue by sritchie** [functional-koans/clojure-koans#19]
Hey guys,

First off, this project kicks ass. I'm one of the committers on https://github.com/nathanmarz/cascalog (along with @nathanmarz), where we struggle daily to help people over that initial conceptual wall.

clojure-koans does this so well that I can't help but think that its structure would be immensely helpful to Cascalog (and really any of the more taxing clojure libraries out there.) Cascalog-Koans, core.logic-koans; all would be excellent companion libraries.

Do you guys have any thoughts on the the idea of extracting the clojure-koan structure, meditations macro etc out into a project or template that could be used by others? I'd be happy to take a crack at this if you're open to it, but don't want to do anything without a blessing and guidance.

Cheers,
Sam

**Comment by zzz6519003** [comment]
like elixir-koans
