### ISSUE TITLE
problem with 08_highter_order_functioins.clj

### ISSUE THREAD

**Issue by lincoln310** [functional-koans/clojure-koans#95]
Hi, i met a assert failed with this:
"Or very weak"
 (= '(:anything :gose :here) (filter (fn [x] true) '(:anything :goes :here)))

am i wrong?

**Comment by trptcolin** [comment]
Looks like just a typo: `:gose` vs. `:goes`. A good tip, whenever you're not sure, is to run `lein repl` and try copy & pasting the expression in there to see what happens.

**Comment by lincoln310** [comment]
opts, i missed that. Thank you..
